name: proceedix_technical_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  fluentui_system_icons: ^1.1.221
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  go_router: ^12.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
